namespace Core.AnalyticServices.CommonEvents
{
    using System;
    using Core.AnalyticServices.Data;

    /*
     * Purchasing
     */
    #region Purchasing
    /// <summary>
    /// Default purchase event class which contains properties common to all purchase events
    /// </summary>
    [Serializable]
    public class IapEvent : IEvent
    {
        /// <summary>
        /// When used alone this is a unique code from the app's store that determines what type
        /// of item or items were purchased.
        /// When combined with the OfferSku this is a unique code tied to the app's store which
        /// determines the price.
        /// </summary>
        public string PriceSku;

        /// <summary>
        /// A unique code tied to the type of item or items that were purchased by the user.
        /// </summary>
        /// <remarks>
        /// Optional
        /// </remarks>
        public string OfferSku;

        /// <summary>
        /// A unique code generated by this app's store that identifies a specific instance of a user purchase.
        /// </summary>
        public string TransactionId;
    }

    /// <summary>
    /// Event fired when an item purchase process starts.
    /// </summary>
    [Serializable]
    public sealed class IapTransactionWillStart : IapEvent
    {
    }

    /// <summary>
    ///  Event fired if app's store purchase fails or does not validate.
    /// </summary>
    [Serializable]
    public sealed class IapTransactionDidFail : IapEvent
    {
        /// <summary>
        /// Description of the error that occurred.
        /// </summary>
        public string ErrorMessage;
    }

    /// <summary>
    /// Event fired on the successful completion of a purchase via the app's store
    /// </summary>
    /// <remarks>
    /// Should not be tied to
    /// </remarks>
    [Serializable]
    public sealed class IapTransactionDidSucceed : IapEvent
    {
        /// <summary>
        /// Receipt provided by this application's purchasing provider
        /// </summary>
        public string Receipt;

        /// <summary>
        /// Identifier of the currency type used for the transaction in ISO 4217 format
        /// </summary>
        /// <remarks>
        /// https://www.iso.org/iso-4217-currency-codes.html
        /// </remarks>
        public string CurrencyCode;

        /// <summary>
        /// Product price to the user at time of transaction in value associated with the
        /// currency type described by CurrencyCode
        /// </summary>
        public double Price;

        /// <summary>
        /// Identify if it's a featured item
        /// </summary>
        public bool Featured;

        /// <summary>
        /// If the purchase was made against a sandbox environment
        /// </summary>
        public bool IsTest;
    }

    /// <summary>
    /// Event fired at the start of the receipt validation process.
    /// </summary>
    [Serializable]
    public sealed class IapWillValidate : IapEvent
    {
    }

    /// <summary>
    /// Event fired after a successful validation.
    /// </summary>
    [Serializable]
    public sealed class IapDidValidate : IapEvent
    {
        /// <summary>
        /// If the validated using a test Receipt.
        /// </summary>
        public bool IsTest;
    }

    /// <summary>
    /// Event fired when the validation process fails.
    /// </summary>
    [Serializable]
    public sealed class IapFailedValidate : IapEvent
    {
        /// <summary>
        /// If the validated using a test Receipt.
        /// </summary>
        public bool IsTest;

        /// <summary>
        /// Description of the error that occurred.
        /// </summary>
        public string ErrorMessage;
    }

    /// <summary>
    /// Event fired when a product gets consumed.
    /// </summary>
    [Serializable]
    public sealed class IapDidConsume : IapEvent
    {
    }

    /// <summary>
    /// Event fired when a transaction gets restored from cache.
    /// </summary>
    [Serializable]
    public sealed class IapDidRestore : IapEvent
    {
    }

    /// <summary>
    /// Event fired when a transaction fails to restore.
    /// </summary>
    [Serializable]
    public sealed class IapFailedRestore : IapEvent
    {
        public String ErrorMessage;
    }

    /// <summary>
    /// Event fired when the manual purchase restoration process for iOS starts.
    /// </summary>
    [Serializable]
    public sealed class IapRestorationProcessWillStart : IEvent
    {
    }

    /// <summary>
    /// Event fired when the manual purchase restoration process for iOS has succeded.
    /// It does not mean that actual purchases has been restored, only that the process has been successful.
    /// </summary>
    [Serializable]
    public sealed class IapRestorationProcessDidSucceed : IEvent
    {
    }

    /// <summary>
    /// Event fired when the manual purchase restoration process for iOS has failed.
    /// </summary>
    [Serializable]
    public sealed class IapRestorationProcessDidFail : IEvent
    {
    }
    #endregion
}